AllCops:
  NewCops: enable
  Exclude:
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'config/*.rb'
    - 'bin/bundle'
Metrics/BlockLength:
  Exclude:
    - 'spec/models/*.rb'
Style/Documentation:
  Exclude:
    - 'app/controllers/*'
    - 'app/models/*'
    - 'app/controllers/api/v1/*'
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/api/v1/requests/*.rb'
    - 'spec/models/*.rb'
