version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2023"
      POSTGRES_USER: "Postgres"
    ports:
      - "5432:5432"
   
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "Postgres2023"
    ports:
      - "16543:80"
    depends_on:
      - postgres
